services:
  prefect:
    image: prefecthq/prefect:2-python3.11
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - mlflow-net

networks:
  mlflow-net:
    external: true
