
services:
  business-logic:
    build: .
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5001
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - .:/app
    working_dir: /app
    command: python your_script.py
    networks:
      - mlflow-net

networks:
  mlflow-net:
    external: true
