
services:
  business-logic:
    build: .
    env_file:
      - .local.env
    volumes:
      - .:/app
    working_dir: /app
    command: python ml.py
    networks:
      - mlflow-net

  terminal:
    build: .
    env_file:
      - .local.env
    volumes:
      - .:/app
    working_dir: /app
    command: ["/bin/bash"]
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - mlflow-net
    

networks:
  mlflow-net:
    external: true
